CL\Slack\Payload\ConversationsHistoryPayloadResponse:
    properties:
        latest:
            type: string
        messages:
            type: array<CL\Slack\Model\SimpleMessage>
        hasMore:
            type: boolean
