CL\Slack\Payload\ConversationsHistoryPayload:
    properties:
        channel:
            type: string
        oldest:
            type: string
        latest:
            type: string
        count:
            type: integer
        inclusive:
            type: boolean
